create table if not exists public.household_state_history (
  id bigint generated by default as identity primary key,
  household_id uuid not null references public.households(id) on delete cascade,
  state jsonb not null,
  version bigint not null,
  created_at timestamptz not null default now(),
  changed_by uuid references auth.users(id) on delete set null
);

create index if not exists household_state_history_household_idx
  on public.household_state_history (household_id, created_at desc);

create index if not exists household_state_history_changed_by_idx
  on public.household_state_history (changed_by);

alter table public.household_state_history enable row level security;

drop policy if exists "members can view state history" on public.household_state_history;
create policy "members can view state history"
on public.household_state_history for select
to authenticated
using ((select private.is_household_member(household_id)));

grant select on public.household_state_history to authenticated;

create or replace function private.archive_household_state()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.household_state_history (household_id, state, version, changed_by)
  values (old.household_id, old.state, old.version, new.updated_by);

  delete from public.household_state_history
  where household_id = old.household_id
    and id not in (
      select id
      from public.household_state_history
      where household_id = old.household_id
      order by created_at desc
      limit 30
    );
  return new;
end;
$$;

revoke all on function private.archive_household_state() from public, anon, authenticated;

drop trigger if exists archive_household_state_before_update on public.household_states;
create trigger archive_household_state_before_update
before update on public.household_states
for each row execute function private.archive_household_state();

create or replace function public.restore_household_state(
  target_household_id uuid,
  target_history_id bigint
)
returns public.household_states
language plpgsql
security definer
set search_path = ''
as $$
declare
  historical_state jsonb;
  restored public.household_states;
begin
  if auth.uid() is null or not private.can_edit_household(target_household_id) then
    raise exception '이 가족 일정의 복원 권한이 없습니다.';
  end if;

  select state into historical_state
  from public.household_state_history
  where id = target_history_id
    and household_id = target_household_id;

  if historical_state is null then
    raise exception '복원할 백업을 찾을 수 없습니다.';
  end if;

  update public.household_states
  set state = historical_state,
      version = version + 1,
      updated_at = now(),
      updated_by = auth.uid()
  where household_id = target_household_id
  returning * into restored;

  return restored;
end;
$$;

revoke all on function public.restore_household_state(uuid, bigint) from public, anon;
grant execute on function public.restore_household_state(uuid, bigint) to authenticated;
