create extension if not exists pg_cron with schema pg_catalog;
create extension if not exists pg_net with schema extensions;

create table if not exists public.event_comments (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  event_key text not null check (char_length(event_key) between 1 and 240),
  body text not null check (char_length(trim(body)) between 1 and 1000),
  author_name text not null default '가족',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.event_checklist_items (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  event_key text not null check (char_length(event_key) between 1 and 240),
  label text not null check (char_length(trim(label)) between 1 and 300),
  done boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.event_attachments (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  event_key text not null check (char_length(event_key) between 1 and 240),
  storage_path text not null unique,
  file_name text not null,
  mime_type text not null default 'application/octet-stream',
  size_bytes bigint not null default 0 check (size_bytes >= 0 and size_bytes <= 10485760),
  uploader_name text not null default '가족',
  uploaded_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  household_id uuid not null references public.households(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  device_label text not null default '브라우저',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.push_delivery_log (
  id bigint generated by default as identity primary key,
  subscription_id uuid not null references public.push_subscriptions(id) on delete cascade,
  notification_key text not null,
  delivered_at timestamptz not null default now(),
  unique (subscription_id, notification_key)
);

create table if not exists public.push_config (
  singleton boolean primary key default true check (singleton),
  public_key text not null,
  private_key text not null,
  created_at timestamptz not null default now()
);

create index if not exists event_comments_lookup_idx on public.event_comments (household_id, event_key, created_at);
create index if not exists event_checklist_lookup_idx on public.event_checklist_items (household_id, event_key, created_at);
create index if not exists event_attachments_lookup_idx on public.event_attachments (household_id, event_key, created_at);
create index if not exists push_subscriptions_household_idx on public.push_subscriptions (household_id);
create index if not exists push_delivery_log_date_idx on public.push_delivery_log (delivered_at);

alter table public.event_comments enable row level security;
alter table public.event_checklist_items enable row level security;
alter table public.event_attachments enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.push_delivery_log enable row level security;
alter table public.push_config enable row level security;

create policy "members can view event comments" on public.event_comments for select to authenticated
using ((select private.is_household_member(household_id)));
create policy "editors can add event comments" on public.event_comments for insert to authenticated
with check ((select private.can_edit_household(household_id)) and created_by = (select auth.uid()));
create policy "authors can delete event comments" on public.event_comments for delete to authenticated
using ((select private.can_edit_household(household_id)) and created_by = (select auth.uid()));

create policy "members can view event checklist" on public.event_checklist_items for select to authenticated
using ((select private.is_household_member(household_id)));
create policy "editors can add event checklist" on public.event_checklist_items for insert to authenticated
with check ((select private.can_edit_household(household_id)) and created_by = (select auth.uid()));
create policy "editors can update event checklist" on public.event_checklist_items for update to authenticated
using ((select private.can_edit_household(household_id)))
with check ((select private.can_edit_household(household_id)) and updated_by = (select auth.uid()));
create policy "editors can delete event checklist" on public.event_checklist_items for delete to authenticated
using ((select private.can_edit_household(household_id)));

create policy "members can view event attachments" on public.event_attachments for select to authenticated
using ((select private.is_household_member(household_id)));
create policy "editors can add event attachments" on public.event_attachments for insert to authenticated
with check ((select private.can_edit_household(household_id)) and uploaded_by = (select auth.uid()));
create policy "editors can delete event attachments" on public.event_attachments for delete to authenticated
using ((select private.can_edit_household(household_id)));

create policy "users can view own push subscriptions" on public.push_subscriptions for select to authenticated
using (user_id = (select auth.uid()) and (select private.is_household_member(household_id)));
create policy "users can add own push subscriptions" on public.push_subscriptions for insert to authenticated
with check (user_id = (select auth.uid()) and (select private.is_household_member(household_id)));
create policy "users can update own push subscriptions" on public.push_subscriptions for update to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()) and (select private.is_household_member(household_id)));
create policy "users can delete own push subscriptions" on public.push_subscriptions for delete to authenticated
using (user_id = (select auth.uid()));

grant select, insert, delete on public.event_comments to authenticated;
grant select, insert, update, delete on public.event_checklist_items to authenticated;
grant select, insert, delete on public.event_attachments to authenticated;
grant select, insert, update, delete on public.push_subscriptions to authenticated;
revoke all on public.push_delivery_log from public, anon, authenticated;
revoke all on public.push_config from public, anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'event-attachments',
  'event-attachments',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'application/pdf', 'text/plain']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "family members can read event files" on storage.objects for select to authenticated
using (
  bucket_id = 'event-attachments'
  and exists (
    select 1 from public.household_members hm
    where hm.household_id::text = (storage.foldername(name))[1]
      and hm.user_id = (select auth.uid())
  )
);
create policy "family editors can upload event files" on storage.objects for insert to authenticated
with check (
  bucket_id = 'event-attachments'
  and exists (
    select 1 from public.household_members hm
    where hm.household_id::text = (storage.foldername(name))[1]
      and hm.user_id = (select auth.uid())
      and hm.can_edit = true
  )
);
create policy "family editors can update event files" on storage.objects for update to authenticated
using (
  bucket_id = 'event-attachments'
  and exists (
    select 1 from public.household_members hm
    where hm.household_id::text = (storage.foldername(name))[1]
      and hm.user_id = (select auth.uid())
      and hm.can_edit = true
  )
)
with check (
  bucket_id = 'event-attachments'
  and exists (
    select 1 from public.household_members hm
    where hm.household_id::text = (storage.foldername(name))[1]
      and hm.user_id = (select auth.uid())
      and hm.can_edit = true
  )
);
create policy "family editors can delete event files" on storage.objects for delete to authenticated
using (
  bucket_id = 'event-attachments'
  and exists (
    select 1 from public.household_members hm
    where hm.household_id::text = (storage.foldername(name))[1]
      and hm.user_id = (select auth.uid())
      and hm.can_edit = true
  )
);

create or replace function public.save_household_state_v2(
  target_household_id uuid,
  next_state jsonb,
  expected_version bigint
)
returns public.household_states
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_version bigint;
  saved public.household_states;
begin
  if auth.uid() is null or not private.can_edit_household(target_household_id) then
    raise exception '이 가족 일정의 수정 권한이 없습니다.';
  end if;

  select version into current_version
  from public.household_states
  where household_id = target_household_id
  for update;

  if current_version is null then
    raise exception '가족 일정 저장소를 찾을 수 없습니다.';
  end if;
  if current_version <> expected_version then
    raise exception using errcode = '40001', message = 'SYNC_CONFLICT';
  end if;

  update public.household_states
  set state = next_state,
      version = version + 1,
      updated_at = now(),
      updated_by = auth.uid()
  where household_id = target_household_id
  returning * into saved;

  return saved;
end;
$$;

revoke all on function public.save_household_state_v2(uuid, jsonb, bigint) from public, anon;
grant execute on function public.save_household_state_v2(uuid, jsonb, bigint) to authenticated;

create or replace function public.get_push_cron_secret()
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller_role text;
  secret_value text;
begin
  caller_role := coalesce(current_setting('request.jwt.claim.role', true), '');
  if caller_role <> 'service_role' then
    raise exception 'forbidden';
  end if;
  select decrypted_secret into secret_value
  from vault.decrypted_secrets
  where name = 'push_cron_secret'
  order by created_at desc
  limit 1;
  return secret_value;
end;
$$;

revoke all on function public.get_push_cron_secret() from public, anon, authenticated;
grant execute on function public.get_push_cron_secret() to service_role;

do $$
begin
  if not exists (select 1 from vault.secrets where name = 'push_cron_secret') then
    perform vault.create_secret(encode(gen_random_bytes(32), 'hex'), 'push_cron_secret', 'Family Scheduler push cron authentication');
  end if;
end;
$$;

do $$
declare
  target_table text;
begin
  foreach target_table in array array['event_comments', 'event_checklist_items', 'event_attachments']
  loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = target_table
    ) then
      execute format('alter publication supabase_realtime add table public.%I', target_table);
    end if;
  end loop;
end;
$$;

do $$
declare
  existing_job bigint;
begin
  select jobid into existing_job from cron.job where jobname = 'family-scheduler-push-minute';
  if existing_job is not null then
    perform cron.unschedule(existing_job);
  end if;
end;
$$;

select cron.schedule(
  'family-scheduler-push-minute',
  '* * * * *',
  $push_job$
    select net.http_post(
      url := 'https://ukzhcimbdxzqzgbzhadk.supabase.co/functions/v1/send-family-push',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'x-cron-secret', (
          select decrypted_secret from vault.decrypted_secrets
          where name = 'push_cron_secret'
          order by created_at desc limit 1
        )
      ),
      body := '{"source":"cron"}'::jsonb,
      timeout_milliseconds := 10000
    );
  $push_job$
);

